services:
  metastore:
    image: postgres:11
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  master:
    image: lanteklcorzo001/hadoop-hive-spark-master
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
      - "10000:10000"
      - "8998:8998"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - ../../Data:/landing
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker1:
    image: lanteklcorzo001/hadoop-hive-spark-worker
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - ../../Data:/landing
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker2:
    image: lanteklcorzo001/hadoop-hive-spark-worker
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
      - ../../Data:/landing
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "history:172.28.1.5"

  history:
    image: lanteklcorzo001/hadoop-hive-spark-history
    hostname: history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: history
    ports:
      - "18080:18080"
      - "19888:19888"
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.5
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"

  dev:
      image: lanteklcorzo001/hadoop-hive-spark-dev
      # stdin_open: true 
      # tty: true        
      hostname: dev
      restart: always
      environment:
        SPARK_MASTER_HOST: 172.28.1.2
        SPARK_LOCAL_IP: 172.28.1.7
        SPARK_LOCAL_HOSTNAME: dev
      ports:
        - "28080:8080"
      volumes:
        - ./dev/home:/home/developer
        - ../../Data:/landing
        - ../../repos:/home/repos
      networks:
        sparknet:
          ipv4_address: 172.28.1.7
      # command: /bin/bash

  jupyter:
    image: lanteklcorzo001/hadoop-hive-spark-jupyter
    hostname: jupyter
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.6
      SPARK_LOCAL_HOSTNAME: jupyter
    depends_on:
      - master
      - worker1
      - worker2
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebook:/home/jupyter
      - ../../Data:/landing
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.6
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"
#Hue
  huedb:
    image: postgres:12.1-alpine
    container_name: huedb
    volumes:
        - pg_data:/var/lib/postgresl/data/
    restart: always
    ports:
      - "5432"
    env_file:
      - ./Hue/hue_db.env
    environment:
        SPARK_MASTER_HOST: 172.28.1.2
        SPARK_LOCAL_IP: 172.28.1.8
        SPARK_LOCAL_HOSTNAME: huedb
    depends_on:
      - master
      - worker1
      - worker2
    networks:
            sparknet:
              ipv4_address: 172.28.1.8
    extra_hosts:
    - "metastore:172.28.1.1"
    - "master:172.28.1.2"
    - "worker1:172.28.1.3"
    - "worker2:172.28.1.4"
    - "history:172.28.1.5"

  hue:
    image: gethue/hue:latest
    container_name: hue
    environment:
        SPARK_MASTER_HOST: 172.28.1.2
        SPARK_LOCAL_IP: 172.28.1.9
        SPARK_LOCAL_HOSTNAME: hue
    ports:
    - "8989:8888"
    volumes:
      - ./Hue/hue_overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
    restart: always
    depends_on:
      - huedb
    networks:
          sparknet:
            ipv4_address: 172.28.1.9
    extra_hosts:
    - "metastore:172.28.1.1"
    - "master:172.28.1.2"
    - "worker1:172.28.1.3"
    - "worker2:172.28.1.4"
    - "history:172.28.1.5"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:
  pg_data:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16