name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: deployment_env
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push BE
        uses: docker/build-push-action@v2
        with:
          context: ./base
          file: Dockerfile
          push: true
          tags: lanteklcorzo001/hue-hadoop-hive-spark-docker-base:latest

      - name: Build and push FE
        uses: docker/build-push-action@v2
        with:
            context: ./master
            file: Dockerfile
            push: true
            tags: lanteklcorzo001/hadoop-hive-spark-master:latest

      - name: Build and push FE
        uses: docker/build-push-action@v2
        with:
              context: ./worker
              file: Dockerfile
              push: true
              tags: lanteklcorzo001/hadoop-hive-spark-worker:latest

      - name: Build and push FE
        uses: docker/build-push-action@v2
        with:
              context: ./history
              file: Dockerfile
              push: true
              tags: lanteklcorzo001/hadoop-hive-spark-history:latest

      - name: Build and push FE
        uses: docker/build-push-action@v2
        with:
              context: ./dev
              file: Dockerfile
              push: true
              tags: lanteklcorzo001/hadoop-hive-spark-dev:latest